-- QuizApp Supabase / PostgreSQL schema
-- Matches the current Spring Boot JPA entities.

create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    password varchar(255) not null,
    role varchar(50) not null,
    identifier varchar(255) not null unique
);

create table if not exists tests (
    id bigint generated by default as identity primary key,
    test_name varchar(255) not null,
    passcode varchar(255) not null,
    teacher_username varchar(255) not null,
    duration integer not null,
    published varchar(10) not null default 'no'
);

create table if not exists questions (
    id bigint generated by default as identity primary key,
    question text not null,
    opt1 text not null,
    opt2 text not null,
    opt3 text not null,
    opt4 text not null,
    correct integer not null,
    test_id bigint not null,
    constraint fk_questions_test
        foreign key (test_id)
        references tests (id)
        on delete cascade
);

create table if not exists results (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    test_id bigint not null,
    score integer not null,
    total integer not null,
    submitted_at timestamp without time zone,
    constraint fk_results_test
        foreign key (test_id)
        references tests (id)
        on delete cascade
);

create index if not exists idx_tests_teacher_username on tests (teacher_username);
create index if not exists idx_tests_published on tests (published);
create index if not exists idx_questions_test_id on questions (test_id);
create index if not exists idx_results_test_id on results (test_id);
create index if not exists idx_results_username on results (username);
